src/Provider/OrderDataProvider.php
=> Ajout order status à la sync incrementale

src/Provider/OrderDataProvider.php
mise au format UTC de add_date
ajout created_at et updated_at aux data envoyées à eventbus
=> Correction created_at et updated_at sur order-status-history

README.md
Add more documentation about version compatibility.
=> Add a compatibility matrix

src/Api/CollectorApiClient.php
Take into account property name and encoding in content-length calculation
=> fix content-length calculation

Makefile, README.md, ps_eventbus.php, upgrade/Upgrade-2.1.0.php
Adding, modifying, or removing a product cover was not registering an incremental sync in the outbox table.
=> Add image hooks for products

ps_eventbus.php, src/Api/SyncApiClient.php, src/Config/Config.php
Makes a call o the sync API every time a hook is triggered
=> add live sync support

src/Provider/ProductSupplierDataProvider.php
remove unwanted comma after last parameter in constructor
=> removing extra coma in constructor

config/front/decorator.yml, config/front/provider.yml, config/front/repository.yml, controllers/front/apiLanguages.php, ps_eventbus.php, src/Config/Config.php, src/Decorator/LanguageDecorator.php, src/Provider/LanguageDataProvider.php, src/Repository/LanguageRepository.php, upgrade/Upgrade-2.3.2.php
Add support for languages synchronization
=> Languages sync

src/Controller/AbstractApiController.php
Fix date offsets in the database on field `last_synced_at` when ps_eventbus syncs data.
=> format date according to shop timezone

controllers/front/apiTranslations.php, src/Config/Config.php, src/Decorator/TranslationDecorator.php, src/Provider/TranslationDataProvider.php, src/Repository/TranslationRepository.php
Ticket JIRA : https://forge.prestashop.com/browse/EB-1067
=> feat: sync translations

src/Repository/CarrierRepository.php
Ticket JIRA : https://forge.prestashop.com/browse/EB-1170
=> fix: remove group-by in get carrier query

README.md, config.xml, ps_eventbus.php
=> Fix semver to 0.0.0

.github/workflows/build-release-publish.yml, Makefile, README.md
As seen with @fox-john & @guillaume60240
=> fix(packaging): Make zip now modifies the version on the fly

e2e-env/README.md
Get precise about recreating the env for testing.
=> fix(doc): enhance E2E env documentation

ps_eventbus.php
Add extra properties, like in ps_metrics and psshipping.
=> fix(main-file): add more settings

Makefile
As used on other projects, I feel this should be backported here as well.
=> fix(makefile): more genericity to share across projects

.config.preprod.yml, .github/workflows/build-release-publish.yml, .gitignore, Makefile
There is no preproduction environment anymore.
=> feat(build): remove preprod support

.github/workflows/build-release-publish.yml
Reverts PrestaShopCorp/ps_eventbus#237
=> Revert "fix(build-release): simplify the build process"

Makefile
rework structure of .phony in makefile
=> feat: rework makefile phony structure

src/Decorator/EmployeeDecorator.php
fix wrong data format when uploading employees
=> fix typing

e2e/src/fixtures/1.7.8.10/apiEmployees/employees.json, src/Decorator/EmployeeDecorator.php
fix type of var "id_shop" for employees shop content.
=> fix: id_shop type variable

.github/workflows/build-release-publish.yml
CI was failing so far: https://github.com/PrestaShopCorp/ps_eventbus/actions/runs/8554139346
=> chore(ci): set the expected PHP version

src/Controller/AbstractApiController.php, src/Service/SynchronizationService.php
Remove all object by shop content in incremental_sync table when full sync is launch for this shop content.
=> feat: delete incremental sync objects when full sync is started

upgrade/Upgrade-3.0.12.php
Add upgrade script for clean incremental and type table when previous version is between 3.0.8 and 3.0.11
=> feat: add upgrade script

src/Repository/ServerInformationRepository.php
apiHealthCheck info were checked with if/else, this can be slightly simplified.
=> Simplify the algorithm

e2e-env/init-scripts/install-module.sh
Now relying on the latest v1.0.4 version.
See: https://github.com/PrestaShopCorp/ps_accounts_mock/releases
=> Fix ps_accounts_mock version

README.md, composer.json, composer.lock, config/common.yml, config/front/repository.yml, controllers/front/apiHealthCheck.php, ps_eventbus.php, src/Decorator/CurrencyDecorator.php, src/Decorator/EmployeeDecorator.php, src/Decorator/StoreDecorator.php, src/DependencyInjection/ContainerProvider.php, src/DependencyInjection/ServiceContainer.php, src/Helper/ModuleHelper.php, src/Repository/CurrencyRepository.php, src/Repository/EmployeeRepository.php, src/Repository/ProductRepository.php, src/Repository/ServerInformationRepository.php, src/Repository/StockRepository.php, src/Repository/StoreRepository.php, src/Repository/WishlistProductRepository.php, src/Repository/WishlistRepository.php
Enhance module compatibility for PrestaShop 1.7.2.5
=> Fix: bugs with Prestashop version < 1.7.3.0

controllers/front/apiHealthCheck.php
Revert missing code for complete apiHealthcheck response
=> fix: healthcheck V2

.github/workflows/build-release-publish.yml, .github/workflows/build-staging.yml
Getting a "staging" rolling release will be very handy for anyone wanting to test the module "en avant première".
=> fix(ci): add staging build support

e2e/src/helpers/data-helper.ts, e2e/src/type/health-check.ts
Fix e2e tests to call new secure healthcheck
=> add jobId to e2e healthcheck

.github/workflows/build-staging.yml
A slight CI issue was preventing our staging releases to ship the correct code.
=> Fix step id

config/front/services.yml, src/Service/SynchronizationService.php
Remove dependency injection of PsAccount into SynchronizationService (fix #330)
=> fix: dependency  injection issue

config/front/services.yml, src/Service/DeletedObjectsService.php, src/Service/SynchronizationService.php
change service called for proxyService
=> fix: error with proxy-interface

config/common.yml, src/Helper/ModuleHelper.php
fix router not found in <= 1.7.5.2 version of PrestaShop
=> fix: router not found

README.md, src/Decorator/ProductDecorator.php
=> fix(product): Unity sync

ps_eventbus.php, src/Repository/CartRuleRepository.php
fix cart rule date send for incremental sync, and fix problem when deleted hook are called.
=> fix: cart rule incremental sync

upgrade/Upgrade-3.2.1.php
add missing upgrade script for 3.2.1 (is needed for reset full sync for cart_rules)
=> feat: add upgrade script for 3.2.1

src/Repository/ImageRepository.php, src/Traits/Hooks/UseCustomerHooks.php, src/Traits/Hooks/UseEmployeeHooks.php, src/Traits/Hooks/UseImageHooks.php, src/Traits/Hooks/UseImageTypeHooks.php, src/Traits/Hooks/UseLanguageHooks.php, src/Traits/Hooks/UseSpecificPriceHooks.php, src/Traits/Hooks/UseStoreHooks.php, src/Traits/Hooks/UseWishlistHooks.php
Fix https://github.com/PrestaShop/PrestaShop/issues/38856
=> Fix: image id hook error after duplication
